// src/app/layout.tsx
//
// ESTE ES EL LAYOUT RAÍZ DE LA APLICACIÓN COMPLETA.
//
// Todo lo que esté dentro de src/app/ se va a renderizar dentro de este layout.
// Encima de los layouts de grupos como (general).
//
// Responsabilidad de este archivo:
// - Definir la estructura HTML base (<html>, <body>).
// - Definir metadata global (título, descripción).
// - Aplicar fuentes globales y clases CSS globales.
// - Envolver TODAS las páginas con lo que quieras poner a nivel global
//   (providers globales, tema, etc.). Aquí lo dejamos limpio.

import type { Metadata } from "next";
// Importamos dos fuentes de Google preconfiguradas por Next
import { Geist, Geist_Mono } from "next/font/google";
// CSS global de la aplicación
import "./globals.css";

// Configuramos la fuente principal (sans serif) y la asociamos
// a una variable CSS que se usará en el body
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configuramos la fuente monoespaciada
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata global de la app (título, descripción, SEO básico)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout es el layout raíz de TODA la app.
// En App Router, TODO lo que haya dentro de src/app se renderiza dentro de este layout.
// Luego dentro de esto se anidan layouts de grupos como (general)/layout.tsx.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // 'children' es la página que se va a mostrar en cada ruta
}>) {
  return (
    <html lang="en">
      <body
        // Aplicamos las variables de fuente al body.
        // 'antialiased' viene de Tailwind y mejora el suavizado de fuentes.
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*
          Aquí van TODAS las páginas.
          
          Orden de renderizado simplificado:
            RootLayout (este)
              -> (general)/layout.tsx
                 -> página concreta (login, feed, posts/[id], etc.)

          Si quisieras manejar autenticación global con Providers (ejemplo <AuthProvider>),
          este sería el lugar para envolver {children} con ellos.

          En este proyecto de notas usamos Zustand desde los componentes cliente,
          así que dejamos RootLayout sin providers adicionales.
        */}
        {children}
      </body>
    </html>
  );
}
